name: Conditional Jobs Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set variables
        id: lang
        run: echo "language=false" >> $GITHUB_OUTPUT
    outputs:
      language: ${{ steps.lang.outputs.language }}
  test:
    if: needs.build.outputs.language == 'true'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Running tests..."
          echo ${{ needs.build.outputs.language }}
