name: Conditional Jobs Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "language=true" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Running tests..."
          echo ${{ needs.build.outputs.language }}

