name: Conditional Jobs Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          LANGUAGE="true"
    outputs:
      language: ${{ $LANGUAGE }}
  test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.language == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests..."
